"""Feature spec constants and classification functions.

All constants and classification logic extracted from the monolithic
feature_engine.py. No I/O imports -- pure data definitions.
"""

from __future__ import annotations

# Standard feature set with default parameters.
# Each entry is (feature_name, params_dict).
DEFAULT_FEATURES: list[tuple[str, dict]] = [
    ("sma", {"period": 5}),
    ("sma", {"period": 10}),
    ("sma", {"period": 20}),
    ("sma", {"period": 60}),
    ("ema", {"period": 12}),
    ("ema", {"period": 26}),
    ("rsi", {"period": 14}),
    ("macd", {}),
    ("bollinger", {"period": 20}),
    ("atr", {"period": 14}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("volume_sma", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("obv", {}),
]


REGIME_FEATURES: list[tuple[str, dict]] = [
    # Existing TA features relevant to volatility prediction
    ("rsi", {"period": 14}),
    ("atr", {"period": 14}),
    ("bollinger", {"period": 20}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("std_vol", {"period": 5}),
    ("std_vol", {"period": 10}),
    # Regime-specific features
    ("vol_ratio", {"short_period": 5, "long_period": 20}),
    ("realized_vol", {"period": 5}),
    ("realized_vol", {"period": 10}),
    ("realized_vol", {"period": 20}),
    ("vol_of_vol", {"vol_period": 20, "meta_period": 10}),
    ("return_autocorr", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("parkinson_vol", {"period": 20}),
    ("garman_klass_vol", {"period": 20}),
]

# Cross-asset pair definitions: maps (market, symbol) -> list of (companion_market, companion_symbol)
# Used by compute_with_companions() to load companion data for cross-asset features.
CROSS_ASSET_PAIRS: dict[tuple[str, str], list[tuple[str, str]]] = {
    ("crypto_spot", "BTCUSDT"): [("crypto_spot", "ETHUSDT")],
    ("crypto_spot", "ETHUSDT"): [("crypto_spot", "BTCUSDT")],
    ("tw_stock", "2330"): [("tw_futures", "TX")],
    ("tw_futures", "TX"): [("tw_stock", "2330")],
}

# Expanded feature set: DEFAULT_FEATURES + volume profile + HMM regime + VIX proxy.
# Cross-asset features (cross_corr, overnight_gap, corr_shift) are NOT listed here --
# they are auto-generated by compute_with_companions() based on CROSS_ASSET_PAIRS.
EXPANDED_FEATURES: list[tuple[str, dict]] = [
    *DEFAULT_FEATURES,
    # Volume profile features (FEAT-02)
    ("vwap_dev", {"period": 20}),
    ("vap_pctile", {"period": 20}),
    ("bs_vol_ratio", {"period": 20}),
    # HMM regime features (FEAT-03)
    ("hmm_regime", {"n_regimes": 3, "vol_period": 20}),
    # VIX proxy (FEAT-04, single-symbol part)
    ("vix_proxy", {"short_period": 5, "long_period": 20}),
]


# -- Non-price feature name sets (used for spec classification + data routing) --------

INSTITUTIONAL_PREFIXES = ("foreign_net_buy", "trust_net_buy", "dealer_net_buy")
FUNDAMENTAL_NAMES = frozenset({"pe_ratio", "pb_ratio", "revenue_mom", "revenue_yoy", "roe", "roa"})
TRADE_STRUCTURE_NAMES = frozenset({"avg_trade_size", "turnover_ratio"})
FUNDING_NAMES = frozenset({"funding_rate_daily", "funding_rate_extreme"})
MARGIN_NAMES = frozenset({"margin_buy_ratio", "margin_sell_ratio"})
OI_NAMES = frozenset({"oi_change", "oi_buildup", "oi_cost_basis"})
PREDICTION_NAMES = frozenset({"qlib_prediction"})
MACRO_PREFIX = "macro_"


def is_nonprice_spec(name: str) -> bool:
    """Return True if the feature name requires non-price data injection."""
    return (
        name.startswith(INSTITUTIONAL_PREFIXES)
        or name in FUNDAMENTAL_NAMES
        or name in TRADE_STRUCTURE_NAMES
        or name in FUNDING_NAMES
        or name in MARGIN_NAMES
        or name in OI_NAMES
        or name in PREDICTION_NAMES
        or name.startswith(MACRO_PREFIX)
    )


def nonprice_data_key(name: str) -> str:
    """Return the kwarg key for the non-price data this feature needs."""
    if name.startswith(INSTITUTIONAL_PREFIXES):
        return "institutional_data"
    if name in FUNDAMENTAL_NAMES:
        return "fundamental_data"
    if name in TRADE_STRUCTURE_NAMES:
        return "trade_structure_data"
    if name in FUNDING_NAMES:
        return "funding_data"
    if name in MARGIN_NAMES:
        return "margin_data"
    if name in OI_NAMES:
        return "oi_data"
    if name in PREDICTION_NAMES:
        return "prediction_data"
    if name.startswith(MACRO_PREFIX):
        return "macro_data"
    raise ValueError(f"Not a non-price feature: {name}")


def get_r2_specs(symbol: str, market: str) -> list[tuple[str, dict]]:
    """Generate market-conditional R2 feature specs.

    Starts from EXPANDED_FEATURES and adds non-price features appropriate
    for the given market:
    - tw_stock: institutional flow + fundamentals + trade structure + macro
    - crypto_spot: funding rate + macro
    - all markets: macro indices

    Args:
        symbol: Symbol identifier (used for documentation; not filtered).
        market: Market name controlling which feature groups are included.

    Returns:
        List of (feature_name, params) tuples.
    """
    specs: list[tuple[str, dict]] = list(EXPANDED_FEATURES)

    if market == "tw_stock":
        specs.extend([
            ("foreign_net_buy_ratio", {}),
            ("foreign_net_buy_cum", {"period": 5}),
            ("foreign_net_buy_cum", {"period": 20}),
            ("trust_net_buy_ratio", {}),
            ("trust_net_buy_cum", {"period": 5}),
            ("trust_net_buy_cum", {"period": 20}),
            ("dealer_net_buy_ratio", {}),
            ("pe_ratio", {}),
            ("pb_ratio", {}),
            ("revenue_mom", {}),
            ("revenue_yoy", {}),
            ("avg_trade_size", {}),
            ("turnover_ratio", {}),
            # Fundamental expansion (Phase 42 FEAT-01)
            ("roe", {}),
            ("roa", {}),
            # Margin transaction (Phase 42 FEAT-02)
            ("margin_buy_ratio", {}),
            ("margin_sell_ratio", {}),
        ])

    if market == "crypto_spot":
        specs.extend([
            ("funding_rate_daily", {}),
        ])

    if market == "crypto_perp":
        specs.extend([
            ("funding_rate_daily", {}),
            ("funding_rate_extreme", {"period": 20, "threshold": 2.0}),
            ("oi_change", {"period": 20}),
            ("oi_buildup", {"period": 24}),
            ("oi_cost_basis", {"period": 168}),
            # Wick & range (G-02)
            ("wick_ratio", {}),
            ("range_expansion", {"period": 14}),
            ("body_ratio", {}),
            # Swing & breakout (G-03)
            ("swing_high", {"period": 24}),
            ("swing_low", {"period": 24}),
            ("breakout_distance", {"period": 24, "atr_period": 14}),
            ("fib_extension", {"period": 24}),
            # Volatility classification (G-04)
            ("atr_percentile", {"period": 14, "lookback": 100}),
            ("vol_regime", {"short_period": 5, "long_period": 20}),
            # Trend filter (G-24)
            ("adx", {"period": 14}),
            ("trend_strength", {"long_period": 100, "atr_period": 14}),
            ("hour_of_day", {}),
        ])

    # Macro indices for ALL markets
    specs.extend([
        ("macro_vix", {}),
        ("macro_dxy", {}),
        ("macro_tnx", {}),
        ("macro_twdusd", {}),
    ])

    return specs


# R2 features are market-conditional -- use get_r2_specs(symbol, market) instead.
# This constant documents the maximum feature set (tw_stock + all markets).
EXPANDED_FEATURES_R2: list[tuple[str, dict]] = [
    *EXPANDED_FEATURES,
    # Institutional (tw_stock only)
    ("foreign_net_buy_ratio", {}),
    ("foreign_net_buy_cum", {"period": 5}),
    ("foreign_net_buy_cum", {"period": 20}),
    ("trust_net_buy_ratio", {}),
    ("trust_net_buy_cum", {"period": 5}),
    ("trust_net_buy_cum", {"period": 20}),
    ("dealer_net_buy_ratio", {}),
    # Fundamental (tw_stock only)
    ("pe_ratio", {}),
    ("pb_ratio", {}),
    ("revenue_mom", {}),
    ("revenue_yoy", {}),
    ("roe", {}),
    ("roa", {}),
    # Trade structure (tw_stock only)
    ("avg_trade_size", {}),
    ("turnover_ratio", {}),
    # Margin transaction (tw_stock only)
    ("margin_buy_ratio", {}),
    ("margin_sell_ratio", {}),
    # Funding (crypto_spot only)
    ("funding_rate_daily", {}),
    # Macro (all markets)
    ("macro_vix", {}),
    ("macro_dxy", {}),
    ("macro_tnx", {}),
    ("macro_twdusd", {}),
]


def get_cross_asset_specs(
    symbol: str, market: str, periods: tuple[int, ...] = (20, 60),
) -> list[tuple[str, dict]]:
    """Generate cross-asset feature specs for a symbol based on CROSS_ASSET_PAIRS.

    Returns list of (feature_name, params) tuples with companion_symbol/companion_market
    populated from CROSS_ASSET_PAIRS config. Returns empty list if no pairs defined.
    """
    pairs = CROSS_ASSET_PAIRS.get((market, symbol), [])
    specs: list[tuple[str, dict]] = []
    for comp_market, comp_symbol in pairs:
        for period in periods:
            specs.append(("cross_corr", {
                "period": period,
                "companion_symbol": comp_symbol,
                "companion_market": comp_market,
            }))
        # Overnight gap (no period)
        specs.append(("overnight_gap", {
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
        # Correlation shift
        specs.append(("corr_shift", {
            "period": 20,
            "shift_period": 5,
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
    return specs
