"""FeatureEngine — single entry point for feature computation.

Used by training, prediction, and backtesting paths.
Loads OHLCV from database, computes requested features, returns wide DataFrame.
"""

import logging
from datetime import datetime

import pandas as pd

from poseidon.autoresearch.guard import autoresearch_guard
from poseidon.data.features.base import get_feature
from poseidon.data.storage import read_ohlcv
from poseidon.models.base import SessionLocal

logger = logging.getLogger(__name__)

# Standard feature set with default parameters.
# Each entry is (feature_name, params_dict).
DEFAULT_FEATURES: list[tuple[str, dict]] = [
    ("sma", {"period": 5}),
    ("sma", {"period": 10}),
    ("sma", {"period": 20}),
    ("sma", {"period": 60}),
    ("ema", {"period": 12}),
    ("ema", {"period": 26}),
    ("rsi", {"period": 14}),
    ("macd", {}),
    ("bollinger", {"period": 20}),
    ("atr", {"period": 14}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("volume_sma", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("obv", {}),
]


REGIME_FEATURES: list[tuple[str, dict]] = [
    # Existing TA features relevant to volatility prediction
    ("rsi", {"period": 14}),
    ("atr", {"period": 14}),
    ("bollinger", {"period": 20}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("std_vol", {"period": 5}),
    ("std_vol", {"period": 10}),
    # Regime-specific features
    ("vol_ratio", {"short_period": 5, "long_period": 20}),
    ("realized_vol", {"period": 5}),
    ("realized_vol", {"period": 10}),
    ("realized_vol", {"period": 20}),
    ("vol_of_vol", {"vol_period": 20, "meta_period": 10}),
    ("return_autocorr", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("parkinson_vol", {"period": 20}),
    ("garman_klass_vol", {"period": 20}),
]

# Cross-asset pair definitions: maps (market, symbol) -> list of (companion_market, companion_symbol)
# Used by compute_with_companions() to load companion data for cross-asset features.
CROSS_ASSET_PAIRS: dict[tuple[str, str], list[tuple[str, str]]] = {
    ("crypto_spot", "BTCUSDT"): [("crypto_spot", "ETHUSDT")],
    ("crypto_spot", "ETHUSDT"): [("crypto_spot", "BTCUSDT")],
    ("tw_stock", "2330"): [("tw_futures", "TX")],
    ("tw_futures", "TX"): [("tw_stock", "2330")],
}

# Expanded feature set: DEFAULT_FEATURES + volume profile + HMM regime + VIX proxy.
# Cross-asset features (cross_corr, overnight_gap, corr_shift) are NOT listed here —
# they are auto-generated by compute_with_companions() based on CROSS_ASSET_PAIRS.
EXPANDED_FEATURES: list[tuple[str, dict]] = [
    *DEFAULT_FEATURES,
    # Volume profile features (FEAT-02)
    ("vwap_dev", {"period": 20}),
    ("vap_pctile", {"period": 20}),
    ("bs_vol_ratio", {"period": 20}),
    # HMM regime features (FEAT-03)
    ("hmm_regime", {"n_regimes": 3, "vol_period": 20}),
    # VIX proxy (FEAT-04, single-symbol part)
    ("vix_proxy", {"short_period": 5, "long_period": 20}),
]


# -- Non-price feature name sets (used for spec classification + data routing) --------

_INSTITUTIONAL_PREFIXES = ("foreign_net_buy", "trust_net_buy", "dealer_net_buy")
_FUNDAMENTAL_NAMES = frozenset({"pe_ratio", "pb_ratio", "revenue_mom", "revenue_yoy", "roe", "roa"})
_TRADE_STRUCTURE_NAMES = frozenset({"avg_trade_size", "turnover_ratio"})
_FUNDING_NAMES = frozenset({"funding_rate_daily", "funding_rate_extreme"})
_MARGIN_NAMES = frozenset({"margin_buy_ratio", "margin_sell_ratio"})
_OI_NAMES = frozenset({"oi_change", "oi_buildup"})
_PREDICTION_NAMES = frozenset({"qlib_prediction"})
_MACRO_PREFIX = "macro_"


def _is_nonprice_spec(name: str) -> bool:
    """Return True if the feature name requires non-price data injection."""
    return (
        name.startswith(_INSTITUTIONAL_PREFIXES)
        or name in _FUNDAMENTAL_NAMES
        or name in _TRADE_STRUCTURE_NAMES
        or name in _FUNDING_NAMES
        or name in _MARGIN_NAMES
        or name in _OI_NAMES
        or name in _PREDICTION_NAMES
        or name.startswith(_MACRO_PREFIX)
    )


def _nonprice_data_key(name: str) -> str:
    """Return the kwarg key for the non-price data this feature needs."""
    if name.startswith(_INSTITUTIONAL_PREFIXES):
        return "institutional_data"
    if name in _FUNDAMENTAL_NAMES:
        return "fundamental_data"
    if name in _TRADE_STRUCTURE_NAMES:
        return "trade_structure_data"
    if name in _FUNDING_NAMES:
        return "funding_data"
    if name in _MARGIN_NAMES:
        return "margin_data"
    if name in _OI_NAMES:
        return "oi_data"
    if name in _PREDICTION_NAMES:
        return "prediction_data"
    if name.startswith(_MACRO_PREFIX):
        return "macro_data"
    raise ValueError(f"Not a non-price feature: {name}")


def get_r2_specs(symbol: str, market: str) -> list[tuple[str, dict]]:
    """Generate market-conditional R2 feature specs.

    Starts from EXPANDED_FEATURES and adds non-price features appropriate
    for the given market:
    - tw_stock: institutional flow + fundamentals + trade structure + macro
    - crypto_spot: funding rate + macro
    - all markets: macro indices

    Args:
        symbol: Symbol identifier (used for documentation; not filtered).
        market: Market name controlling which feature groups are included.

    Returns:
        List of (feature_name, params) tuples.
    """
    specs: list[tuple[str, dict]] = list(EXPANDED_FEATURES)

    if market == "tw_stock":
        specs.extend([
            ("foreign_net_buy_ratio", {}),
            ("foreign_net_buy_cum", {"period": 5}),
            ("foreign_net_buy_cum", {"period": 20}),
            ("trust_net_buy_ratio", {}),
            ("trust_net_buy_cum", {"period": 5}),
            ("trust_net_buy_cum", {"period": 20}),
            ("dealer_net_buy_ratio", {}),
            ("pe_ratio", {}),
            ("pb_ratio", {}),
            ("revenue_mom", {}),
            ("revenue_yoy", {}),
            ("avg_trade_size", {}),
            ("turnover_ratio", {}),
            # Fundamental expansion (Phase 42 FEAT-01)
            ("roe", {}),
            ("roa", {}),
            # Margin transaction (Phase 42 FEAT-02)
            ("margin_buy_ratio", {}),
            ("margin_sell_ratio", {}),
        ])

    if market == "crypto_spot":
        specs.extend([
            ("funding_rate_daily", {}),
        ])

    if market == "crypto_perp":
        specs.extend([
            ("funding_rate_daily", {}),
            ("funding_rate_extreme", {"period": 20, "threshold": 2.0}),
            ("oi_change", {"period": 20}),
            ("oi_buildup", {"period": 24}),
            # Wick & range (G-02)
            ("wick_ratio", {}),
            ("range_expansion", {"period": 14}),
            ("body_ratio", {}),
            # Swing & breakout (G-03)
            ("swing_high", {"period": 24}),
            ("swing_low", {"period": 24}),
            ("breakout_distance", {"period": 24, "atr_period": 14}),
            ("fib_extension", {"period": 24}),
            # Volatility classification (G-04)
            ("atr_percentile", {"period": 14, "lookback": 100}),
            ("vol_regime", {"short_period": 5, "long_period": 20}),
            # Trend filter (G-24)
            ("adx", {"period": 14}),
            ("trend_strength", {"long_period": 100, "atr_period": 14}),
            ("hour_of_day", {}),
        ])

    # Macro indices for ALL markets
    specs.extend([
        ("macro_vix", {}),
        ("macro_dxy", {}),
        ("macro_tnx", {}),
        ("macro_twdusd", {}),
    ])

    return specs


# R2 features are market-conditional -- use get_r2_specs(symbol, market) instead.
# This constant documents the maximum feature set (tw_stock + all markets).
EXPANDED_FEATURES_R2: list[tuple[str, dict]] = [
    *EXPANDED_FEATURES,
    # Institutional (tw_stock only)
    ("foreign_net_buy_ratio", {}),
    ("foreign_net_buy_cum", {"period": 5}),
    ("foreign_net_buy_cum", {"period": 20}),
    ("trust_net_buy_ratio", {}),
    ("trust_net_buy_cum", {"period": 5}),
    ("trust_net_buy_cum", {"period": 20}),
    ("dealer_net_buy_ratio", {}),
    # Fundamental (tw_stock only)
    ("pe_ratio", {}),
    ("pb_ratio", {}),
    ("revenue_mom", {}),
    ("revenue_yoy", {}),
    ("roe", {}),
    ("roa", {}),
    # Trade structure (tw_stock only)
    ("avg_trade_size", {}),
    ("turnover_ratio", {}),
    # Margin transaction (tw_stock only)
    ("margin_buy_ratio", {}),
    ("margin_sell_ratio", {}),
    # Funding (crypto_spot only)
    ("funding_rate_daily", {}),
    # Macro (all markets)
    ("macro_vix", {}),
    ("macro_dxy", {}),
    ("macro_tnx", {}),
    ("macro_twdusd", {}),
]


def get_cross_asset_specs(
    symbol: str, market: str, periods: tuple[int, ...] = (20, 60),
) -> list[tuple[str, dict]]:
    """Generate cross-asset feature specs for a symbol based on CROSS_ASSET_PAIRS.

    Returns list of (feature_name, params) tuples with companion_symbol/companion_market
    populated from CROSS_ASSET_PAIRS config. Returns empty list if no pairs defined.
    """
    pairs = CROSS_ASSET_PAIRS.get((market, symbol), [])
    specs: list[tuple[str, dict]] = []
    for comp_market, comp_symbol in pairs:
        for period in periods:
            specs.append(("cross_corr", {
                "period": period,
                "companion_symbol": comp_symbol,
                "companion_market": comp_market,
            }))
        # Overnight gap (no period)
        specs.append(("overnight_gap", {
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
        # Correlation shift
        specs.append(("corr_shift", {
            "period": 20,
            "shift_period": 5,
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
    return specs


@autoresearch_guard
class FeatureEngine:
    """Compute features from OHLCV data.

    This is the single computation entry point. Training, prediction, and
    backtesting all use the same FeatureEngine to avoid train-serve skew.

    Two modes of operation:
    - compute(): loads OHLCV from DB, computes features, returns wide DataFrame
    - compute_from_df(): computes features from an already-loaded DataFrame
    """

    def compute(
        self,
        symbol: str,
        market: str,
        interval: str,
        start: datetime | None = None,
        end: datetime | None = None,
        feature_specs: list[tuple[str, dict]] | None = None,
    ) -> pd.DataFrame:
        """Load OHLCV from database and compute features.

        Args:
            symbol: Symbol identifier (e.g., "2330", "AAPL", "BTCUSDT")
            market: Market name (e.g., "tw_stock", "us_stock", "crypto_spot")
            interval: Candle interval ("1d", "1h")
            start: Start datetime (inclusive). None for all available data.
            end: End datetime (inclusive). None for up to latest.
            feature_specs: List of (feature_name, params_dict). None uses DEFAULT_FEATURES.

        Returns:
            Wide DataFrame with columns: time, open, high, low, close, volume, + feature columns.
            Empty DataFrame if no OHLCV data found.
        """
        session = SessionLocal()
        try:
            ohlcv = read_ohlcv(session, symbol, market, interval, start, end)
        finally:
            session.close()

        if ohlcv.empty:
            logger.warning("No OHLCV data for %s/%s/%s", market, symbol, interval)
            return ohlcv

        return self.compute_from_df(ohlcv, feature_specs)

    def compute_from_df(
        self,
        ohlcv: pd.DataFrame,
        feature_specs: list[tuple[str, dict]] | None = None,
    ) -> pd.DataFrame:
        """Compute features from an already-loaded OHLCV DataFrame.

        This is the core computation method. compute() delegates to this
        after loading data. Backtesting uses this directly when OHLCV
        is already in memory.

        Args:
            ohlcv: DataFrame with columns [time, open, high, low, close, volume].
            feature_specs: List of (feature_name, params_dict). None uses DEFAULT_FEATURES.

        Returns:
            Wide DataFrame with original OHLCV columns + computed feature columns.
        """
        if ohlcv.empty:
            return ohlcv

        specs = feature_specs if feature_specs is not None else DEFAULT_FEATURES
        result = ohlcv.copy()

        for feature_name, params in specs:
            feature_cls = get_feature(feature_name)
            feature = feature_cls()
            computed = feature.compute(ohlcv, **params)

            if isinstance(computed, pd.Series):
                result[computed.name] = computed
            elif isinstance(computed, pd.DataFrame):
                for col in computed.columns:
                    result[col] = computed[col]

        logger.info(
            "Computed %d feature specs -> %d columns (from %d OHLCV rows)",
            len(specs),
            len(result.columns) - len(ohlcv.columns),
            len(ohlcv),
        )
        return result

    def compute_with_companions(
        self,
        ohlcv: pd.DataFrame,
        symbol: str,
        market: str,
        interval: str,
        feature_specs: list[tuple[str, dict]] | None = None,
        db_session=None,
        extra_nonprice_data: dict[str, pd.DataFrame] | None = None,
    ) -> pd.DataFrame:
        """Compute features including cross-asset and non-price data features.

        Three categories of feature specs:
        1. Single-symbol: standard TA features computed from OHLCV only.
        2. Cross-asset: specs with ``companion_symbol`` in params; loads
           companion OHLCV from DB.
        3. Non-price: specs whose name maps to external data (institutional
           flow, fundamentals, trade structure, funding rates, macro indices).
           Data is loaded lazily via loaders and injected as kwargs.

        Args:
            ohlcv: Primary symbol OHLCV DataFrame.
            symbol: Primary symbol identifier.
            market: Primary market name.
            interval: Candle interval.
            feature_specs: Feature specifications. None uses DEFAULT_FEATURES.
            db_session: SQLAlchemy session for loading companion data. If None, creates one.
            extra_nonprice_data: Externally-injected non-price data to merge
                into the loader results. Used by BacktestRunner to inject
                prediction cache data (e.g., ``{"prediction_data": df}``).

        Returns:
            Wide DataFrame with OHLCV + all computed feature columns.
        """
        if ohlcv.empty:
            return ohlcv

        specs = feature_specs if feature_specs is not None else DEFAULT_FEATURES

        # Separate single-symbol, cross-asset, and non-price specs
        single_specs: list[tuple[str, dict]] = []
        cross_specs: list[tuple[str, dict]] = []
        nonprice_specs: list[tuple[str, dict]] = []
        for name, params in specs:
            if "companion_symbol" in params:
                cross_specs.append((name, params))
            elif _is_nonprice_spec(name):
                nonprice_specs.append((name, params))
            else:
                single_specs.append((name, params))

        # Compute single-symbol features first
        result = self.compute_from_df(ohlcv, single_specs) if single_specs else ohlcv.copy()

        has_external = bool(cross_specs) or bool(nonprice_specs)
        if not has_external:
            return result

        # Load companion data and compute cross-asset features
        close_session = False
        if db_session is None:
            db_session = SessionLocal()
            close_session = True

        try:
            # --- Cross-asset features ---
            companion_cache: dict[tuple[str, str], pd.DataFrame] = {}

            for feature_name, params in cross_specs:
                comp_symbol = params.get("companion_symbol", "")
                comp_market = params.get("companion_market", market)
                cache_key = (comp_market, comp_symbol)

                if cache_key not in companion_cache:
                    companion_cache[cache_key] = read_ohlcv(
                        db_session, comp_symbol, comp_market, interval,
                    )

                companion_df = companion_cache[cache_key]
                feature_cls = get_feature(feature_name)
                feature = feature_cls()
                computed = feature.compute(
                    ohlcv,
                    companion_data=companion_df if not companion_df.empty else None,
                    **params,
                )

                if isinstance(computed, pd.Series):
                    result[computed.name] = computed
                elif isinstance(computed, pd.DataFrame):
                    for col in computed.columns:
                        result[col] = computed[col]

            # --- Non-price data features ---
            if nonprice_specs:
                nonprice_data = self._load_nonprice_data(
                    nonprice_specs, symbol,
                )
                # Merge externally-injected non-price data (e.g., prediction_data
                # from BacktestRunner). External data takes precedence over loader.
                if extra_nonprice_data:
                    nonprice_data.update(extra_nonprice_data)
                for feature_name, params in nonprice_specs:
                    data_key = _nonprice_data_key(feature_name)
                    extra_kwargs = {data_key: nonprice_data.get(data_key)}

                    feature_cls = get_feature(feature_name)
                    feature = feature_cls()
                    computed = feature.compute(ohlcv, **params, **extra_kwargs)

                    if isinstance(computed, pd.Series):
                        result[computed.name] = computed
                    elif isinstance(computed, pd.DataFrame):
                        for col in computed.columns:
                            result[col] = computed[col]
        finally:
            if close_session:
                db_session.close()

        logger.info(
            "Computed %d single + %d cross-asset + %d non-price specs -> %d total columns",
            len(single_specs),
            len(cross_specs),
            len(nonprice_specs),
            len(result.columns) - len(ohlcv.columns),
        )
        return result

    @staticmethod
    def _load_nonprice_data(
        nonprice_specs: list[tuple[str, dict]],
        symbol: str,
    ) -> dict[str, pd.DataFrame]:
        """Lazily load non-price data required by the given specs.

        Only instantiates loaders and fetches data when the corresponding
        feature names are present in *nonprice_specs*.
        """
        nonprice_data: dict[str, pd.DataFrame] = {}

        needs_institutional = any(
            n.startswith(_INSTITUTIONAL_PREFIXES) for n, _ in nonprice_specs
        )
        needs_fundamental = any(n in _FUNDAMENTAL_NAMES for n, _ in nonprice_specs)
        needs_trade_structure = any(n in _TRADE_STRUCTURE_NAMES for n, _ in nonprice_specs)
        needs_funding = any(n in _FUNDING_NAMES for n, _ in nonprice_specs)
        needs_margin = any(n in _MARGIN_NAMES for n, _ in nonprice_specs)
        needs_oi = any(n in _OI_NAMES for n, _ in nonprice_specs)
        needs_macro = any(n.startswith(_MACRO_PREFIX) for n, _ in nonprice_specs)

        if needs_institutional or needs_fundamental or needs_trade_structure or needs_margin:
            from poseidon.data.loaders import FinLabDataLoader

            finlab = FinLabDataLoader()
            if needs_institutional:
                nonprice_data["institutional_data"] = finlab.get_institutional_flow(symbol)
            if needs_fundamental:
                nonprice_data["fundamental_data"] = finlab.get_fundamentals(symbol)
            if needs_trade_structure:
                nonprice_data["trade_structure_data"] = finlab.get_trade_structure(symbol)
            if needs_margin:
                nonprice_data["margin_data"] = finlab.get_margin_data(symbol)

        if needs_funding:
            from poseidon.data.loaders import FundingRateLoader

            nonprice_data["funding_data"] = FundingRateLoader().get_daily_funding_rate(symbol)

        if needs_oi:
            from poseidon.data.loaders import OpenInterestLoader

            nonprice_data["oi_data"] = OpenInterestLoader(
                session_factory=SessionLocal
            ).get_oi_series(symbol)

        if needs_macro:
            from poseidon.data.loaders import MacroIndexLoader

            nonprice_data["macro_data"] = MacroIndexLoader().get_macro_data()

        return nonprice_data
