"""FeatureEngine — single entry point for feature computation.

Used by training, prediction, and backtesting paths.
Loads OHLCV from database, computes requested features, returns wide DataFrame.
"""

import logging
from datetime import datetime

import pandas as pd

from poseidon.autoresearch.guard import autoresearch_guard
from poseidon.data.features.base import get_feature
from poseidon.data.storage import read_ohlcv
from poseidon.models.base import SessionLocal

logger = logging.getLogger(__name__)

# Standard feature set with default parameters.
# Each entry is (feature_name, params_dict).
DEFAULT_FEATURES: list[tuple[str, dict]] = [
    ("sma", {"period": 5}),
    ("sma", {"period": 10}),
    ("sma", {"period": 20}),
    ("sma", {"period": 60}),
    ("ema", {"period": 12}),
    ("ema", {"period": 26}),
    ("rsi", {"period": 14}),
    ("macd", {}),
    ("bollinger", {"period": 20}),
    ("atr", {"period": 14}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("volume_sma", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("obv", {}),
]


REGIME_FEATURES: list[tuple[str, dict]] = [
    # Existing TA features relevant to volatility prediction
    ("rsi", {"period": 14}),
    ("atr", {"period": 14}),
    ("bollinger", {"period": 20}),
    ("returns", {}),
    ("std_vol", {"period": 20}),
    ("std_vol", {"period": 5}),
    ("std_vol", {"period": 10}),
    # Regime-specific features
    ("vol_ratio", {"short_period": 5, "long_period": 20}),
    ("realized_vol", {"period": 5}),
    ("realized_vol", {"period": 10}),
    ("realized_vol", {"period": 20}),
    ("vol_of_vol", {"vol_period": 20, "meta_period": 10}),
    ("return_autocorr", {"period": 20}),
    ("volume_ratio", {"period": 20}),
    ("parkinson_vol", {"period": 20}),
    ("garman_klass_vol", {"period": 20}),
]

# Cross-asset pair definitions: maps (market, symbol) -> list of (companion_market, companion_symbol)
# Used by compute_with_companions() to load companion data for cross-asset features.
CROSS_ASSET_PAIRS: dict[tuple[str, str], list[tuple[str, str]]] = {
    ("crypto_spot", "BTCUSDT"): [("crypto_spot", "ETHUSDT")],
    ("crypto_spot", "ETHUSDT"): [("crypto_spot", "BTCUSDT")],
    ("tw_stock", "2330"): [("tw_futures", "TX")],
    ("tw_futures", "TX"): [("tw_stock", "2330")],
}

# Expanded feature set: DEFAULT_FEATURES + volume profile + HMM regime + VIX proxy.
# Cross-asset features (cross_corr, overnight_gap, corr_shift) are NOT listed here —
# they are auto-generated by compute_with_companions() based on CROSS_ASSET_PAIRS.
EXPANDED_FEATURES: list[tuple[str, dict]] = [
    *DEFAULT_FEATURES,
    # Volume profile features (FEAT-02)
    ("vwap_dev", {"period": 20}),
    ("vap_pctile", {"period": 20}),
    ("bs_vol_ratio", {"period": 20}),
    # HMM regime features (FEAT-03)
    ("hmm_regime", {"n_regimes": 3, "vol_period": 20}),
    # VIX proxy (FEAT-04, single-symbol part)
    ("vix_proxy", {"short_period": 5, "long_period": 20}),
]


def get_cross_asset_specs(
    symbol: str, market: str, periods: tuple[int, ...] = (20, 60),
) -> list[tuple[str, dict]]:
    """Generate cross-asset feature specs for a symbol based on CROSS_ASSET_PAIRS.

    Returns list of (feature_name, params) tuples with companion_symbol/companion_market
    populated from CROSS_ASSET_PAIRS config. Returns empty list if no pairs defined.
    """
    pairs = CROSS_ASSET_PAIRS.get((market, symbol), [])
    specs: list[tuple[str, dict]] = []
    for comp_market, comp_symbol in pairs:
        for period in periods:
            specs.append(("cross_corr", {
                "period": period,
                "companion_symbol": comp_symbol,
                "companion_market": comp_market,
            }))
        # Overnight gap (no period)
        specs.append(("overnight_gap", {
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
        # Correlation shift
        specs.append(("corr_shift", {
            "period": 20,
            "shift_period": 5,
            "companion_symbol": comp_symbol,
            "companion_market": comp_market,
        }))
    return specs


@autoresearch_guard
class FeatureEngine:
    """Compute features from OHLCV data.

    This is the single computation entry point. Training, prediction, and
    backtesting all use the same FeatureEngine to avoid train-serve skew.

    Two modes of operation:
    - compute(): loads OHLCV from DB, computes features, returns wide DataFrame
    - compute_from_df(): computes features from an already-loaded DataFrame
    """

    def compute(
        self,
        symbol: str,
        market: str,
        interval: str,
        start: datetime | None = None,
        end: datetime | None = None,
        feature_specs: list[tuple[str, dict]] | None = None,
    ) -> pd.DataFrame:
        """Load OHLCV from database and compute features.

        Args:
            symbol: Symbol identifier (e.g., "2330", "AAPL", "BTCUSDT")
            market: Market name (e.g., "tw_stock", "us_stock", "crypto_spot")
            interval: Candle interval ("1d", "1h")
            start: Start datetime (inclusive). None for all available data.
            end: End datetime (inclusive). None for up to latest.
            feature_specs: List of (feature_name, params_dict). None uses DEFAULT_FEATURES.

        Returns:
            Wide DataFrame with columns: time, open, high, low, close, volume, + feature columns.
            Empty DataFrame if no OHLCV data found.
        """
        session = SessionLocal()
        try:
            ohlcv = read_ohlcv(session, symbol, market, interval, start, end)
        finally:
            session.close()

        if ohlcv.empty:
            logger.warning("No OHLCV data for %s/%s/%s", market, symbol, interval)
            return ohlcv

        return self.compute_from_df(ohlcv, feature_specs)

    def compute_from_df(
        self,
        ohlcv: pd.DataFrame,
        feature_specs: list[tuple[str, dict]] | None = None,
    ) -> pd.DataFrame:
        """Compute features from an already-loaded OHLCV DataFrame.

        This is the core computation method. compute() delegates to this
        after loading data. Backtesting uses this directly when OHLCV
        is already in memory.

        Args:
            ohlcv: DataFrame with columns [time, open, high, low, close, volume].
            feature_specs: List of (feature_name, params_dict). None uses DEFAULT_FEATURES.

        Returns:
            Wide DataFrame with original OHLCV columns + computed feature columns.
        """
        if ohlcv.empty:
            return ohlcv

        specs = feature_specs if feature_specs is not None else DEFAULT_FEATURES
        result = ohlcv.copy()

        for feature_name, params in specs:
            feature_cls = get_feature(feature_name)
            feature = feature_cls()
            computed = feature.compute(ohlcv, **params)

            if isinstance(computed, pd.Series):
                result[computed.name] = computed
            elif isinstance(computed, pd.DataFrame):
                for col in computed.columns:
                    result[col] = computed[col]

        logger.info(
            "Computed %d feature specs -> %d columns (from %d OHLCV rows)",
            len(specs),
            len(result.columns) - len(ohlcv.columns),
            len(ohlcv),
        )
        return result

    def compute_with_companions(
        self,
        ohlcv: pd.DataFrame,
        symbol: str,
        market: str,
        interval: str,
        feature_specs: list[tuple[str, dict]] | None = None,
        db_session=None,
    ) -> pd.DataFrame:
        """Compute features including cross-asset ones that need companion data.

        For cross-asset feature specs (those with companion_symbol in params),
        loads companion data from DB and injects it into the feature's params.
        Single-symbol features work as before via compute_from_df().

        Args:
            ohlcv: Primary symbol OHLCV DataFrame.
            symbol: Primary symbol identifier.
            market: Primary market name.
            interval: Candle interval.
            feature_specs: Feature specifications. None uses DEFAULT_FEATURES.
            db_session: SQLAlchemy session for loading companion data. If None, creates one.

        Returns:
            Wide DataFrame with OHLCV + all computed feature columns.
        """
        if ohlcv.empty:
            return ohlcv

        specs = feature_specs if feature_specs is not None else DEFAULT_FEATURES

        # Separate single-symbol and cross-asset specs
        single_specs = []
        cross_specs = []
        for name, params in specs:
            if "companion_symbol" in params:
                cross_specs.append((name, params))
            else:
                single_specs.append((name, params))

        # Compute single-symbol features first
        result = self.compute_from_df(ohlcv, single_specs) if single_specs else ohlcv.copy()

        if not cross_specs:
            return result

        # Load companion data and compute cross-asset features
        close_session = False
        if db_session is None:
            db_session = SessionLocal()
            close_session = True

        try:
            # Cache companion data to avoid redundant DB reads
            companion_cache: dict[tuple[str, str], pd.DataFrame] = {}

            for feature_name, params in cross_specs:
                comp_symbol = params.get("companion_symbol", "")
                comp_market = params.get("companion_market", market)
                cache_key = (comp_market, comp_symbol)

                if cache_key not in companion_cache:
                    companion_cache[cache_key] = read_ohlcv(
                        db_session, comp_symbol, comp_market, interval,
                    )

                companion_df = companion_cache[cache_key]
                feature_cls = get_feature(feature_name)
                feature = feature_cls()
                computed = feature.compute(
                    ohlcv,
                    companion_data=companion_df if not companion_df.empty else None,
                    **params,
                )

                if isinstance(computed, pd.Series):
                    result[computed.name] = computed
                elif isinstance(computed, pd.DataFrame):
                    for col in computed.columns:
                        result[col] = computed[col]
        finally:
            if close_session:
                db_session.close()

        logger.info(
            "Computed %d single + %d cross-asset specs -> %d total columns",
            len(single_specs),
            len(cross_specs),
            len(result.columns) - len(ohlcv.columns),
        )
        return result
